import type { G02GroupContext, G02Progress, G02Store } from './types'
import { g02CurrentStatus } from './validation'

export const G02_STORAGE_KEY = 'qijing-training-demo:g02:v1'
export function createEmptyG02Store(): G02Store { return { version: 1, groups: {} } }
export function createInitialG02Progress(context: G02GroupContext): G02Progress { const allEvidence = context.memberEvidence.flatMap((member) => member.evidence); const firstWeb = allEvidence.find((item) => item.type === 'M08 互动网页'); return { version: 1, groupId: context.groupId, groupName: context.groupName, rosterFingerprint: context.rosterFingerprint, evidenceFingerprint: context.evidenceFingerprint, route: 'overview', memberEvidence: context.memberEvidence, directoryConfirmed: false, showcase: { title: `${context.groupName}多模态教学成果展示`, teachingScenario: '围绕同一课次，从教师讲授、数字人微课到学生互动练习形成连续学习路径。', artifactIds: allEvidence.map((item) => item.artifactId), onlineDemoArtifactId: firstWeb?.artifactId ?? '', onlineInteractionName: '展开知识卡并完成即时反馈题', onlineInteractionTested: false, confirmed: false }, feedback: context.seedFeedback, feedbackConfirmed: false, revision: { feedbackId: context.seedFeedback[0]?.feedbackId ?? '', before: '展示页首屏仅列出成果文件名称。', after: '展示页首屏按课件导学、视频讲解、网页练习、选修拓展呈现学习路径。', basis: context.seedFeedback[0]?.feedback ?? '', contributorParticipantId: context.memberEvidence[0]?.participantId ?? '', applied: false }, contributions: context.seedContributions, contributionsConfirmed: false, artifacts: [], assessmentModificationSummary: '', assessments: [], currentStatus: '待验收', updatedAt: new Date().toISOString() } }
export function synchronizeG02Progress(progress: G02Progress, context: G02GroupContext): G02Progress { if (progress.groupId !== context.groupId || progress.rosterFingerprint !== context.rosterFingerprint || progress.evidenceFingerprint !== context.evidenceFingerprint) { const fresh = createInitialG02Progress(context); return { ...fresh, assessments: progress.assessments, currentStatus: progress.assessments.length ? '需补验' : '待验收' } } const next = { ...progress, groupName: context.groupName, memberEvidence: context.memberEvidence, feedback: context.seedFeedback, contributions: context.seedContributions.map((seed) => { const existing = progress.contributions.find((item) => item.participantId === seed.participantId); return existing && existing.source === seed.source ? existing : seed }) }; return { ...next, currentStatus: g02CurrentStatus(next) } }
export function g02ProgressForGroup(store: G02Store, context: G02GroupContext) { const existing = store.groups[context.groupId]; return existing ? synchronizeG02Progress(existing, context) : createInitialG02Progress(context) }
export function updateGroupG02Progress(store: G02Store, context: G02GroupContext, updater: (progress: G02Progress) => G02Progress): G02Store { const next = updater(g02ProgressForGroup(store, context)); return { ...store, groups: { ...store.groups, [context.groupId]: { ...next, currentStatus: g02CurrentStatus(next), updatedAt: new Date().toISOString() } } } }
export function clearGroupG02Progress(store: G02Store, groupId: string) { const groups = { ...store.groups }; delete groups[groupId]; return { ...store, groups } }
export function clearAllG02Progress() { if (typeof window !== 'undefined') window.localStorage.removeItem(G02_STORAGE_KEY); return createEmptyG02Store() }
export function invalidateAllG02Progress(store: G02Store, now = new Date().toISOString()): G02Store { return { ...store, groups: Object.fromEntries(Object.entries(store.groups).map(([groupId, progress]) => [groupId, { ...progress, rosterFingerprint: `invalidated:${now}`, evidenceFingerprint: `invalidated:${now}`, memberEvidence: [], directoryConfirmed: false, artifacts: [], currentStatus: progress.assessments.length ? '需补验' : '待验收', updatedAt: now }])) } }
export function loadG02Store(storage: Pick<Storage, 'getItem'> = window.localStorage): G02Store { try { const parsed = JSON.parse(storage.getItem(G02_STORAGE_KEY) ?? 'null') as G02Store | null; return parsed?.version === 1 && parsed.groups ? parsed : createEmptyG02Store() } catch { return createEmptyG02Store() } }
export function saveG02Store(store: G02Store, storage: Pick<Storage, 'setItem'> = window.localStorage) { storage.setItem(G02_STORAGE_KEY, JSON.stringify(store)) }
