import { g02OutputNames } from './data'
import type { G02AcceptanceCondition, G02ArtifactSnapshot, G02GroupContext, G02Progress, G02StageStatus } from './types'

function hash(value: unknown) { const text = JSON.stringify(value); let result = 2166136261; for (let index = 0; index < text.length; index += 1) { result ^= text.charCodeAt(index); result = Math.imul(result, 16777619) } return (result >>> 0).toString(36) }
export function g02ContentFingerprint(progress: G02Progress) { return `g02-${hash({ groupId: progress.groupId, roster: progress.rosterFingerprint, evidence: progress.evidenceFingerprint, directoryConfirmed: progress.directoryConfirmed, showcase: progress.showcase, feedback: progress.feedback, feedbackConfirmed: progress.feedbackConfirmed, revision: progress.revision, contributions: progress.contributions, contributionsConfirmed: progress.contributionsConfirmed })}` }
export function g02EvidenceTypesComplete(progress: G02Progress) { const types = new Set(progress.memberEvidence.flatMap((member) => member.evidence.map((item) => item.type))); return ['M06 课件','M06 可播放视频','M08 互动网页','首个选修成果'].every((type) => types.has(type as never)) && progress.memberEvidence.flatMap((member) => member.evidence).some((item) => item.type === 'M06 可播放视频' && item.playable) }
export function g02ContributionsComplete(progress: G02Progress) { const members = new Set(progress.memberEvidence.map((item) => item.participantId)); return progress.contributionsConfirmed && [...members].every((participantId) => progress.contributions.some((item) => item.participantId === participantId && item.role && item.contribution.trim() && item.artifactId.trim())) }
export function g02Conditions(progress: G02Progress): G02AcceptanceCondition[] {
  const showcaseComplete = progress.directoryConfirmed && progress.showcase.confirmed && progress.showcase.title.trim() && progress.showcase.teachingScenario.trim() && g02EvidenceTypesComplete(progress) && progress.showcase.artifactIds.length === progress.memberEvidence.flatMap((member) => member.evidence).length
  const online = progress.memberEvidence.flatMap((member) => member.evidence).find((item) => item.artifactId === progress.showcase.onlineDemoArtifactId && item.type === 'M08 互动网页' && item.interactive)
  const validFeedback = progress.feedback.filter((item) => item.received && item.sourceGroupId !== progress.groupId && item.feedback.trim())
  const revisionValid = progress.feedbackConfirmed && validFeedback.length >= 2 && validFeedback.some((item) => item.feedbackId === progress.revision.feedbackId) && progress.revision.applied && progress.revision.before.trim() && progress.revision.after.trim() && progress.revision.before.trim() !== progress.revision.after.trim() && progress.revision.basis.trim() && progress.memberEvidence.some((item) => item.participantId === progress.revision.contributorParticipantId)
  return [
    { id: 'showcase-completeness', label: '展示页同时包含 M06 课件、可播放视频、M08 网页和首个选修成果', passed: Boolean(showcaseComplete), evidence: showcaseComplete ? '四类成果均已聚合到当前一页式展示页' : '展示页确认、四类成果或完整成果目录仍需补齐' },
    { id: 'member-contribution', label: '小组每位成员至少贡献 1 项作品或完成 1 处实质修改', passed: g02ContributionsComplete(progress), evidence: `${progress.contributions.filter((item) => item.role && item.contribution.trim() && item.artifactId.trim()).length}/${progress.memberEvidence.length} 名成员已有贡献记录` },
    { id: 'online-interaction', label: '现场在线演示至少 1 个可操作互动并记录测试结果', passed: Boolean(online && progress.showcase.onlineInteractionName.trim() && progress.showcase.onlineInteractionTested), evidence: online && progress.showcase.onlineInteractionTested ? `已演示：${progress.showcase.onlineInteractionName}` : '尚未选择 M08 互动网页并确认在线操作成功' },
    { id: 'feedback-revision', label: '收到不少于 2 条具体跨组反馈，并据反馈修改至少 1 处且标明贡献者', passed: Boolean(revisionValid), evidence: revisionValid ? `收到 ${validFeedback.length} 条反馈，已由指定成员完成一处前后可辨的修改` : `当前有效跨组反馈 ${validFeedback.length}/2 条，反馈修改或贡献者记录仍需完成` },
  ]
}
export function validateG02Directory(progress: G02Progress) { const messages: string[] = []; if (!progress.memberEvidence.length) messages.push('当前分组没有成员，无法建立小组成果目录'); if (progress.memberEvidence.some((member) => member.evidence.length !== 4)) messages.push('每位成员必须具有 M06 课件、M06 视频、M08 网页和首个选修成果四类目录项'); if (!progress.directoryConfirmed) messages.push('请确认小组成果目录及模拟来源边界'); return { valid: messages.length === 0, messages } }
export function validateG02Showcase(progress: G02Progress) { const messages = [...validateG02Directory(progress).messages]; if (!g02Conditions(progress)[0].passed) messages.push('请完成一页式展示页标题、教学场景、四类成果聚合和小组确认'); if (!g02Conditions(progress)[2].passed) messages.push('请选用 M08 网页在线演示至少 1 个互动并确认操作成功'); return { valid: messages.length === 0, messages: [...new Set(messages)] } }
export function validateG02Feedback(progress: G02Progress) { const messages: string[] = []; if (progress.feedback.filter((item) => item.received && item.sourceGroupId !== progress.groupId && item.feedback.trim()).length < 2) messages.push('必须收到不少于 2 条来自其他小组的具体反馈'); if (!progress.feedbackConfirmed) messages.push('请确认小组已共同阅读并判断两条跨组反馈'); return { valid: messages.length === 0, messages } }
export function validateG02Revision(progress: G02Progress) { const conditions = g02Conditions(progress), messages = [...validateG02Feedback(progress).messages]; if (!conditions[3].passed) messages.push('请选用一条跨组反馈，记录修改前、修改后、依据和实际贡献成员'); if (!conditions[1].passed) messages.push('请确认每位成员至少贡献 1 项作品或完成 1 处实质修改'); return { valid: messages.length === 0, messages: [...new Set(messages)] } }
export function g02ArtifactsAreCurrent(progress: G02Progress) { const fingerprint = g02ContentFingerprint(progress); return progress.artifacts.length === 3 && g02OutputNames.every((name) => progress.artifacts.some((item) => item.name === name && item.fingerprint === fingerprint)) }
export function createG02Artifacts(progress: G02Progress): G02ArtifactSnapshot[] { const fingerprint = g02ContentFingerprint(progress), capturedAt = new Date().toISOString(); return g02OutputNames.map((name, index) => ({ artifactId: `G02:${progress.groupId}:${index + 1}:${fingerprint}`, name, capturedAt, fingerprint, summary: index === 0 ? `${progress.showcase.title} · 四类成果 · ${progress.showcase.onlineInteractionName}` : index === 1 ? `${progress.feedback.length} 条跨组反馈 · 1 处反馈修改` : `${progress.contributions.length} 名成员贡献记录` })) }
export function latestG02AssessmentIsCurrent(progress: G02Progress) { const latest = progress.assessments.at(-1); return Boolean(latest?.outcome === '已通过' && latest.fingerprint === g02ContentFingerprint(progress) && g02ArtifactsAreCurrent(progress)) }
export function g02CurrentStatus(progress: G02Progress): G02StageStatus { if (latestG02AssessmentIsCurrent(progress)) return '已通过'; const latest = progress.assessments.at(-1); if (latest?.outcome === '未通过' && latest.fingerprint === g02ContentFingerprint(progress)) return '未通过'; if (latest) return '需补验'; return '待验收' }
export function validateG02Assessment(progress: G02Progress) { const messages = [...validateG02Showcase(progress).messages, ...validateG02Revision(progress).messages]; if (!g02Conditions(progress).every((item) => item.passed)) messages.push('四项小组里程碑验收条件必须全部通过'); return { valid: messages.length === 0, messages: [...new Set(messages)] } }
export function progressForG02(progress: G02Progress) { const stages = [validateG02Directory(progress).valid, validateG02Showcase(progress).valid, validateG02Feedback(progress).valid, validateG02Revision(progress).valid, g02Conditions(progress).every((item) => item.passed), latestG02AssessmentIsCurrent(progress)]; return Math.round(stages.filter(Boolean).length / stages.length * 100) }
export function createG02Assessment(progress: G02Progress) { const conditions = g02Conditions(progress), passed = conditions.every((item) => item.passed), artifacts = passed ? createG02Artifacts(progress) : []; return { assessment: { assessmentId: `g02-assessment-${Date.now()}`, phase: progress.assessments.length ? '补验' as const : '初验' as const, outcome: passed ? '已通过' as const : '未通过' as const, submittedAt: new Date().toISOString(), assessor: '培训师', method: '本地规则引擎（Demo）' as const, fingerprint: g02ContentFingerprint(progress), failedConditionIds: conditions.filter((item) => !item.passed).map((item) => item.id), conditions, modificationSummary: progress.assessmentModificationSummary, artifacts }, artifacts } }
