import type { ParticipantDirectory } from '../training/types'
import { createInitialE06Progress } from './data'
import type { E06ConfirmedPackage, E06Progress } from './domain'
import { e06ComparisonFingerprint, e06Hash, e06InputFingerprint, e06LiteratureFingerprint } from './runner'
import { e06ConfirmationFingerprint, validateE06Confirmation } from './validation'

export const E06_STORAGE_KEY = 'ai-literacy-training:e06:v1'
export interface E06ProgressStore { version: 1; participants: Record<string, E06Progress> }
export function loadE06Store(): E06ProgressStore { if (typeof window === 'undefined') return { version: 1, participants: {} }; try { const parsed = JSON.parse(window.localStorage.getItem(E06_STORAGE_KEY) ?? '') as E06ProgressStore; return parsed?.version === 1 && parsed.participants ? parsed : { version: 1, participants: {} } } catch { return { version: 1, participants: {} } } }
export function saveE06Store(store: E06ProgressStore) { if (typeof window !== 'undefined') window.localStorage.setItem(E06_STORAGE_KEY, JSON.stringify(store)) }
export function e06ProgressForParticipant(store: E06ProgressStore, participantId: string) { return store.participants[participantId] ?? createInitialE06Progress() }
export function updateParticipantE06Progress(store: E06ProgressStore, participantId: string, updater: (current: E06Progress) => E06Progress): E06ProgressStore { return { ...store, participants: { ...store.participants, [participantId]: { ...updater(e06ProgressForParticipant(store, participantId)), updatedAt: new Date().toISOString() } } } }
export function clearParticipantE06Progress(store: E06ProgressStore, participantId: string) { const participants = { ...store.participants }; delete participants[participantId]; const next = { ...store, participants }; saveE06Store(next); return next }
export function clearAllE06Progress(): E06ProgressStore { if (typeof window !== 'undefined') window.localStorage.removeItem(E06_STORAGE_KEY); return { version: 1, participants: {} } }
export function createConfirmedE06Package(progress: E06Progress, directory: ParticipantDirectory): E06ConfirmedPackage | undefined { const participant = directory.participants.find((item) => item.participantId === directory.currentParticipantId); if (!participant || !validateE06Confirmation(progress, directory).valid) return undefined; const confirmationFingerprint = e06ConfirmationFingerprint(progress, directory); const packageId = `E06-PKG-${e06Hash([participant.participantId, confirmationFingerprint])}`; return { packageId, participantId: participant.participantId, groupId: participant.groupId, confirmedAt: new Date().toISOString(), confirmationFingerprint, question: progress.source.teachingQuestion, sourceFingerprint: e06InputFingerprint(progress), literatureFingerprint: e06LiteratureFingerprint(progress), comparisonFingerprint: e06ComparisonFingerprint(progress), artifacts: [{ artifactId: `${packageId}:literature-review`, kind: 'e06-literature-review', name: '文献梳理表' }, { artifactId: `${packageId}:comparison-table`, kind: 'e06-comparison-table', name: '观点对比表' }, { artifactId: `${packageId}:citation-audit`, kind: 'e06-citation-audit', name: '引用核验记录' }] } }
