import type {
  TeacherAssessmentResult,
  TeacherGrowthState,
  TeacherTrainingPlan,
} from "./types"

export const completedTeacherAssessment: TeacherAssessmentResult = {
  status: "completed",
  stage: "baseline",
  score: 64,
  level: "L2 AI实践者",
  completedAt: "2026-07-15 10:30",
  dimensions: [
    { label: "AI 基础认知", score: 72, target: 85, evidence: "理论题 8/10；能够识别生成式 AI 的基本边界。" },
    { label: "提示词与多模态", score: 68, target: 82, evidence: "能完成结构化提示，但缺少多轮校验与多模态约束。" },
    { label: "知识库与智能体", score: 51, target: 78, evidence: "理解检索增强概念，尚未独立完成智能体编排。" },
    { label: "教学融合", score: 74, target: 86, evidence: "能将 AI 用于备课与评价，课堂应用证据较完整。" },
    { label: "研究创新", score: 47, target: 75, evidence: "具备研究问题意识，引用核验和 AI 披露流程待加强。" },
  ],
  typeScores: [
    { label: "理论题", score: 73 },
    { label: "情境判断", score: 69 },
    { label: "实操任务", score: 51 },
  ],
  strengths: ["教学情境判断准确", "能够识别隐私与事实核验风险", "已有提示词结构化意识"],
  gaps: ["知识库检索与引用链路", "科研智能体的工具编排", "AI 使用披露与人工确认流程"],
  recommendedGoals: ["完成知识库与智能体基础实训", "建立科研引用核验清单", "产出 1 个可复用的教学智能体"],
}

export function createTeacherTrainingPlan(): TeacherTrainingPlan {
  return {
    id: "teacher-growth-plan-01",
    title: "李老师 · AI 能力提升计划",
    weeklyHours: 4,
    durationWeeks: 6,
    status: "draft",
    updatedAt: "2026-07-15 10:31",
    modules: [
      {
        id: "module-foundation",
        title: "生成式 AI 基础与安全边界",
        ability: "AI 基础认知",
        required: true,
        enabled: true,
        duration: 90,
        status: "not-started",
        resourceIds: ["resource-foundation-video"],
        reason: "巩固基础概念，并统一事实核验和数据安全规范。",
      },
      {
        id: "module-prompt",
        title: "提示词工程与多模态表达",
        ability: "提示词与多模态",
        required: true,
        enabled: true,
        duration: 120,
        status: "not-started",
        resourceIds: ["resource-prompt-guide"],
        reason: "补齐多轮约束、质量评价与多模态任务拆解。",
      },
      {
        id: "module-agent",
        title: "知识库与智能体编排",
        ability: "知识库与智能体",
        required: true,
        enabled: true,
        duration: 180,
        status: "not-started",
        resourceIds: ["resource-rag-video", "resource-agent-lab"],
        reason: "当前最低维度，优先建立检索、引用与工具调用能力。",
      },
      {
        id: "module-teaching",
        title: "AI 教学融合案例研习",
        ability: "教学融合",
        required: true,
        enabled: true,
        duration: 100,
        status: "not-started",
        resourceIds: ["resource-teaching-case"],
        reason: "将已有教学经验沉淀为可复用流程与评价证据。",
      },
      {
        id: "module-research",
        title: "科研智能体与研究规范",
        ability: "研究创新",
        required: false,
        enabled: true,
        duration: 150,
        status: "not-started",
        resourceIds: ["resource-research-guide"],
        reason: "选修强化引用核验、匿名化和 AI 使用披露。",
      },
    ],
  }
}

export function createInitialTeacherGrowthState(): TeacherGrowthState {
  return {
    assessment: {
      status: "not-started",
      stage: "baseline",
      score: 0,
      level: "L1 AI入门者",
      dimensions: completedTeacherAssessment.dimensions.map((dimension) => ({ ...dimension, score: 0 })),
      typeScores: completedTeacherAssessment.typeScores.map((item) => ({ ...item, score: 0 })),
      strengths: [],
      gaps: [],
      recommendedGoals: [],
    },
    trainingPlan: null,
    resources: [
      {
        id: "resource-foundation-video",
        title: "生成式 AI 基础与可信使用",
        type: "视频",
        source: "校本教师发展资源库",
        version: "v2.1",
        duration: 36,
        ability: "AI 基础认知",
        imported: true,
        favorite: false,
        progress: 0,
        completed: false,
        note: "",
      },
      {
        id: "resource-prompt-guide",
        title: "结构化提示词与多模态任务指南",
        type: "文档",
        source: "省级 AI 通识课程包",
        version: "v1.4",
        duration: 45,
        ability: "提示词与多模态",
        imported: true,
        favorite: true,
        progress: 20,
        completed: false,
        note: "用角色、目标、约束、评价四段式改造备课提示词。",
      },
      {
        id: "resource-rag-video",
        title: "知识库检索与来源引用",
        type: "视频",
        source: "高校教师 AI 能力课程",
        version: "v3.0",
        duration: 52,
        ability: "知识库与智能体",
        imported: true,
        favorite: false,
        progress: 0,
        completed: false,
        note: "",
      },
      {
        id: "resource-agent-lab",
        title: "科研资料整理智能体实训",
        type: "实训",
        source: "启境实训任务包",
        version: "v1.2",
        duration: 80,
        ability: "知识库与智能体",
        imported: true,
        favorite: false,
        progress: 0,
        completed: false,
        note: "",
      },
      {
        id: "resource-teaching-case",
        title: "AI 支持形成性评价案例",
        type: "案例",
        source: "优秀教学案例库",
        version: "2026 春",
        duration: 40,
        ability: "教学融合",
        imported: true,
        favorite: false,
        progress: 0,
        completed: false,
        note: "",
      },
      {
        id: "resource-research-guide",
        title: "教育科研中的 AI 使用与披露规范",
        type: "文档",
        source: "校级科研规范库",
        version: "v1.0",
        duration: 35,
        ability: "研究创新",
        imported: true,
        favorite: false,
        progress: 0,
        completed: false,
        note: "",
      },
    ],
    recommendedPath: {
      resourceIds: [
        "resource-foundation-video",
        "resource-rag-video",
        "resource-agent-lab",
        "resource-research-guide",
        "resource-prompt-guide",
        "resource-teaching-case",
      ],
      saved: true,
      updatedAt: "由摸底结果生成",
    },
    customPath: {
      resourceIds: ["resource-prompt-guide", "resource-agent-lab"],
      saved: false,
      updatedAt: "尚未保存",
    },
    practiceRecords: [],
    evidenceLedger: [
      {
        id: "growth-evidence-teaching-seed",
        teacherId: "teacher-li",
        source: "智能备课与教学实施",
        task: "采纳并发布《生成式视觉设计》情境化教案",
        course: "生成式视觉设计",
        artifactVersion: "情境化教案 v1.3",
        dimensions: ["教学融合", "提示词与多模态"],
        reviewStatus: "已确认",
        anonymous: true,
        abilityImpact: "教学融合 +4",
        completedAt: "2026-07-30 10:18",
      },
      {
        id: "growth-evidence-practice-seed",
        teacherId: "teacher-li",
        source: "自由实训",
        task: "提示词实验室：形成性评价提示词对比",
        course: "教师个人实训",
        artifactVersion: "实验记录 v2",
        dimensions: ["提示词与多模态"],
        reviewStatus: "已确认",
        anonymous: false,
        abilityImpact: "提示词与多模态 +3",
        completedAt: "2026-07-29 16:40",
      },
      {
        id: "growth-evidence-research-seed",
        teacherId: "teacher-li",
        source: "AI研究和科研智能体",
        task: "课堂互动研究助理关联阶段成果",
        course: "匿名课堂行动研究",
        artifactVersion: "研究备忘录 v1.0",
        dimensions: ["研究创新", "知识库与智能体"],
        reviewStatus: "已确认",
        anonymous: true,
        abilityImpact: "研究创新 +4",
        completedAt: "2026-07-28 14:25",
      },
      {
        id: "growth-evidence-learning-seed",
        teacherId: "teacher-li",
        source: "课程学习",
        task: "完成《生成式 AI 基础与可信使用》",
        course: "教师 AI 通识课程",
        artifactVersion: "学习记录 v1",
        dimensions: ["AI 基础认知"],
        reviewStatus: "已确认",
        anonymous: false,
        abilityImpact: "AI 基础认知 +2",
        completedAt: "2026-07-27 19:20",
      },
      {
        id: "growth-evidence-grading-seed",
        teacherId: "teacher-li",
        source: "AI批改和人工复核",
        task: "复核边界作品的 AI 评分",
        course: "生成式视觉设计",
        artifactVersion: "评分复核 v2",
        dimensions: ["教学融合"],
        reviewStatus: "已确认",
        anonymous: true,
        abilityImpact: "教学融合 +2",
        completedAt: "2026-07-27 15:10",
      },
      {
        id: "growth-evidence-intervention-seed",
        teacherId: "teacher-li",
        source: "分层干预",
        task: "发布负向提示词补强任务",
        course: "生成式视觉设计",
        artifactVersion: "干预方案 v1",
        dimensions: ["教学融合"],
        reviewStatus: "已确认",
        anonymous: true,
        abilityImpact: "教学融合 +3",
        completedAt: "2026-07-26 11:05",
      },
      {
        id: "growth-evidence-retest-seed",
        teacherId: "teacher-li",
        source: "结业复测",
        task: "完成阶段能力复测",
        course: "教师个人成长",
        artifactVersion: "阶段复测 v1",
        dimensions: ["AI 基础认知", "提示词与多模态", "知识库与智能体", "教学融合", "研究创新"],
        reviewStatus: "已确认",
        anonymous: false,
        abilityImpact: "综合能力 +5",
        completedAt: "2026-07-25 17:30",
      },
    ],
    researchAgent: {
      projectId: "project-001",
      name: "课堂互动研究助理",
      persona: "协助教师整理匿名课堂观察记录、归纳证据并生成带来源引用的研究备忘录。",
      sourceIds: ["source-001", "source-002"],
      toolIds: ["rag", "deep-research"],
      version: 1,
      status: "draft",
      checks: {
        citations: true,
        manualReview: true,
        anonymousData: true,
        aiDisclosure: true,
      },
    },
  }
}
