import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, FileArchive, FileCheck2, History, LockKeyhole, RefreshCw, ShieldCheck, UsersRound, XCircle } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { g01OutputNames } from '../g01/data'
import type { G01ChecklistCategory, G01ChecklistItem, G01Contribution, G01CrossCheck, G01ErrorCorrection, G01Progress } from '../g01/types'
import { g01ChecklistComplete, g01ContributionsComplete, g01CrossChecksComplete, g01ErrorsComplete, g01IsCurrentlyPassed, g01PrerequisitesComplete, validateG01Assessment } from '../g01/validation'
import type { GroupRole } from '../types'

const groupRoles: GroupRole[] = ['协调员', '操作员', '核验员', '记录员', '展示员', '学生体验员']
const checklistCategories: G01ChecklistCategory[] = ['事实', '引用', '安全', '目标', '答案']
const simulationDisclosure = '当前为无多人后端的模拟组员成果，不代表真实提交。'

function TextField({ label, value, onChange, rows = 3, disabled = false }: { label: string; value: string; onChange: (value: string) => void; rows?: number; disabled?: boolean }) {
  return <label className="field"><span>{label}</span><textarea rows={rows} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} /></label>
}

function SimulationNotice({ visible }: { visible: boolean }) {
  if (!visible) return null
  return <div className="review-source-note g01-disclosure" role="note"><AlertTriangle size={18} /><div><strong>{simulationDisclosure}</strong><p>当前教师优先读取已有本地成果，缺项使用明确标注的“任务内演示成果”；其他成员按 participantId 与 groupId 确定性生成只读摘要。</p></div></div>
}

function statusClass(status: G01Progress['currentStatus']): string { return status === '已通过' ? 'completed' : status === '待验收' ? 'ready' : 'blocked' }

export function G01Overview({ progress, onNext }: { progress: G01Progress; onNext: () => void }) {
  const complete = g01PrerequisitesComplete(progress)
  const simulated = progress.memberPrerequisites.some((item) => item.source === '模拟组员摘要')
  return <><PageHeader eyebrow="步骤 1 / 6 · 任务说明与材料基线" title="教学设计与命题成果验收" description="G01 可独立开始：已有 M01—M05 成果优先复用；缺项使用明确标注的任务内演示成果。" aside={<div className="metric-pill"><ClipboardCheck size={18} /><span><strong>30 分钟</strong><small>阶段验收 · 小组共创</small></span></div>} />
    {!complete && <section className="result-banner"><LockKeyhole size={26} /><div><strong>验收材料需要恢复</strong><p>当前小组材料状态异常，可使用任务内重置恢复确定性演示材料；该操作不会改写 M01—M05。</p></div><span>材料异常</span></section>}
    <SimulationNotice visible={simulated} />
    <section className="content-card g01-prerequisite-panel"><div className="section-heading"><div><span className="eyebrow">GROUP EVIDENCE</span><h2>{progress.groupName}验收材料矩阵</h2></div><span className={`status-pill ${statusClass(progress.currentStatus)}`}>{progress.currentStatus}</span></div>
      <div className="g01-prerequisite-table"><div className="g01-table-head"><span>成员 / 来源</span>{['M01 核验', 'M02 评分', 'M03 双版本', 'M04 教案', 'M05 题目包'].map((label) => <span key={label}>{label}</span>)}</div>{progress.memberPrerequisites.map((member) => <div className="g01-table-row" key={member.participantId}><span><strong>{member.participantName}</strong><small>{member.isCurrentParticipant ? `当前教师 · ${member.source}` : '模拟组员摘要'}</small></span>{member.evidence.map((item) => <span className={item.complete ? 'passed' : 'missing'} key={item.taskId}>{item.complete ? <CheckCircle2 size={16} /> : <XCircle size={16} />}<small>{item.artifactIds.length ? `${item.artifactIds.length} 个引用` : '未完成'}</small></span>)}</div>)}</div>
    </section>
    <section className="content-card g01-facts"><div><span>教学场景</span><strong>备课成果复核、同伴互评</strong></div><div><span>核心知识点</span><strong>事实核验、目标对齐、教师审校</strong></div><div><span>核心技能点</span><strong>交叉检查、问题归纳、协作记录</strong></div></section>
    <div className="page-actions"><span>{complete ? '所有成员五类验收材料齐全，可以建立小组成果目录' : '请重置当前小组以恢复验收材料'}</span><button className="primary-button" type="button" disabled={!complete} onClick={onNext}>建立成果目录<ArrowRight size={17} /></button></div></>
}

export function G01DirectoryPage({ progress, onNext }: { progress: G01Progress; onNext: () => void }) {
  return <><PageHeader eyebrow="步骤 2 / 6 · 小组成果目录" title="汇总每位成员的五类验收材料" description="目录明确区分真实本地成果、当前教师的任务内演示成果和模拟组员摘要；所有演示数据仅用于 G01，绝不反写上游任务状态。" aside={<div className="metric-pill"><UsersRound size={18} /><span><strong>{progress.memberPrerequisites.length} 名成员</strong><small>{progress.groupName}</small></span></div>} /><SimulationNotice visible={progress.memberPrerequisites.some((item) => item.source === '模拟组员摘要')} />
    <div className="g01-member-directory">{progress.memberPrerequisites.map((member) => <section className="content-card" key={member.participantId}><div className="section-heading"><div><span className="eyebrow">{member.participantId}</span><h2>{member.participantName}</h2></div><span className={`status-pill ${member.isCurrentParticipant ? 'completed' : 'framework'}`}>{member.source}</span></div><div className="g01-evidence-list">{member.evidence.map((item) => <article key={item.taskId}><span>{item.taskId}</span><div><strong>{item.label}</strong><small>{item.artifactIds.join('、') || '暂无当前引用'}</small></div>{item.complete ? <CheckCircle2 size={17} /> : <XCircle size={17} />}</article>)}</div></section>)}</div>
    <section className="content-card g01-output-contract"><div className="section-heading"><div><span className="eyebrow">EXACT OUTPUT CONTRACT</span><h2>小组成果恰好三项</h2></div><span>不得合并、改名或新增</span></div>{g01OutputNames.map((name, index) => <article key={name}><span>0{index + 1}</span><strong>{name}</strong><FileArchive size={18} /></article>)}</section>
    <div className="page-actions"><span>目录将随当前成果指纹一同进入阶段验收快照</span><button className="primary-button" type="button" onClick={onNext}>核对错误与修正<ArrowRight size={17} /></button></div></>
}

export function G01ErrorsPage({ progress, onUpdate, onNext }: { progress: G01Progress; onUpdate: (participantId: string, patch: Partial<G01ErrorCorrection>) => void; onNext: () => void }) {
  const complete = g01ErrorsComplete(progress)
  return <><PageHeader eyebrow="步骤 3 / 6 · AI 错误与教师修正" title="每位成员展示 1 处错误与教师修正" description="每条记录必须引用来源成果，并同时保留 AI 错误、教师修正和修正依据；真实记录、任务内演示成果与模拟组员摘要均明确标注来源。" /><SimulationNotice visible={progress.errorCorrections.some((item) => item.source === '模拟组员摘要')} />
    <div className="g01-record-grid">{progress.errorCorrections.map((record) => { const editable = record.source !== '模拟组员摘要'; return <section className="content-card g01-record-card" key={record.participantId}><div className="section-heading"><div><span className="eyebrow">{record.participantId}</span><h2>{record.participantName}</h2></div><span className={`status-pill ${editable ? 'completed' : 'framework'}`}>{record.source}</span></div><div className="form-grid"><label className="field"><span>来源任务</span><select disabled={!editable} value={record.sourceTaskId} onChange={(event) => onUpdate(record.participantId, { sourceTaskId: event.target.value as G01ErrorCorrection['sourceTaskId'] })}>{['M01','M02','M03','M04'].map((item) => <option key={item}>{item}</option>)}</select></label><TextField label="来源成果 ID" rows={2} disabled={!editable} value={record.sourceArtifactId} onChange={(sourceArtifactId) => onUpdate(record.participantId, { sourceArtifactId })} /></div><TextField label="AI 错误" disabled={!editable} value={record.aiError} onChange={(aiError) => onUpdate(record.participantId, { aiError })} /><TextField label="教师修正" disabled={!editable} value={record.teacherCorrection} onChange={(teacherCorrection) => onUpdate(record.participantId, { teacherCorrection })} /><TextField label="修正依据" disabled={!editable} value={record.correctionBasis} onChange={(correctionBasis) => onUpdate(record.participantId, { correctionBasis })} /></section> })}</div>
    <div className={complete ? 'validation success' : 'validation error'}>{complete ? <CheckCircle2 size={18} /> : <AlertTriangle size={18} />}<span>{complete ? '每位成员均有一处可追溯的 AI 错误与教师修正。' : '仍有成员缺少来源、错误、教师修正或修正依据。'}</span></div>
    <div className="page-actions"><span>内容变化会改变当前成果指纹，旧通过记录不会继续生效</span><button className="primary-button" type="button" disabled={!complete} onClick={onNext}>检查交叉复核<ArrowRight size={17} /></button></div></>
}

export function G01CrossChecksPage({ progress, onUpdate, onNext }: { progress: G01Progress; onUpdate: (participantId: string, patch: Partial<G01CrossCheck>) => void; onNext: () => void }) {
  const complete = g01CrossChecksComplete(progress)
  return <><PageHeader eyebrow="步骤 4 / 6 · 教案或题目包交叉检查" title="每位成员至少交叉检查 1 份成果" description="检查人和被检查人必须是同组不同成员，记录教案或题目包引用、发现与结论。" /><SimulationNotice visible={progress.crossChecks.some((item) => item.source === '模拟组员摘要')} />
    <div className="g01-record-grid">{progress.crossChecks.map((record) => { const editable = record.source !== '模拟组员摘要'; return <section className="content-card g01-record-card" key={record.reviewerParticipantId}><div className="section-heading"><div><span className="eyebrow">REVIEWER</span><h2>{record.reviewerName}</h2></div><span className={`status-pill ${editable ? 'completed' : 'framework'}`}>{record.source}</span></div><div className="form-grid"><label className="field"><span>被检查成员</span><select disabled={!editable} value={record.targetParticipantId} onChange={(event) => { const target = progress.memberPrerequisites.find((item) => item.participantId === event.target.value); onUpdate(record.reviewerParticipantId, { targetParticipantId: event.target.value, targetParticipantName: target?.participantName ?? '', targetArtifactId: '' }) }}><option value="">请选择</option>{progress.memberPrerequisites.filter((item) => item.participantId !== record.reviewerParticipantId).map((item) => <option key={item.participantId} value={item.participantId}>{item.participantName}</option>)}</select></label><label className="field"><span>成果类型</span><select disabled={!editable} value={record.artifactType} onChange={(event) => onUpdate(record.reviewerParticipantId, { artifactType: event.target.value as G01CrossCheck['artifactType'] })}><option>教案</option><option>题目包</option></select></label></div><TextField label="成果引用 ID" rows={2} disabled={!editable} value={record.targetArtifactId} onChange={(targetArtifactId) => onUpdate(record.reviewerParticipantId, { targetArtifactId })} /><TextField label="交叉检查发现" disabled={!editable} value={record.finding} onChange={(finding) => onUpdate(record.reviewerParticipantId, { finding })} /><label className="field"><span>检查结论</span><select disabled={!editable} value={record.conclusion} onChange={(event) => onUpdate(record.reviewerParticipantId, { conclusion: event.target.value as G01CrossCheck['conclusion'] })}><option value="">请选择</option><option>通过</option><option>需修改</option></select></label></section> })}</div>
    <div className={complete ? 'validation success' : 'validation error'}>{complete ? <CheckCircle2 size={18} /> : <AlertTriangle size={18} />}<span>{complete ? '每位成员均完成至少一次同组交叉检查。' : '仍有成员缺少有效交叉检查，检查自己不计入完成。'}</span></div>
    <div className="page-actions"><span>交叉检查引用 M04 教案或 M05 题目包，不复制任务编辑器</span><button className="primary-button" type="button" disabled={!complete} onClick={onNext}>汇总核验清单<ArrowRight size={17} /></button></div></>
}

export function G01ChecklistPage({ progress, onUpdateChecklist, onAddChecklist, onRemoveChecklist, onUpdateContribution, onNext }: { progress: G01Progress; onUpdateChecklist: (id: string, patch: Partial<G01ChecklistItem>) => void; onAddChecklist: () => void; onRemoveChecklist: (id: string) => void; onUpdateContribution: (participantId: string, patch: Partial<G01Contribution>) => void; onNext: () => void }) {
  const checklistComplete = g01ChecklistComplete(progress); const contributionComplete = g01ContributionsComplete(progress)
  return <><PageHeader eyebrow="步骤 5 / 6 · 核验清单与个人贡献" title="形成不少于 8 项的五类核验清单" description="清单只要求不少于 8 项并覆盖事实、引用、安全、目标和答案；不设置字数门槛。同步记录每位成员的任务角色和具体贡献。" aside={<button className="secondary-button" type="button" onClick={onAddChecklist}>新增核验项</button>} /><SimulationNotice visible={progress.contributions.some((item) => item.source === '模拟组员摘要')} />
    <section className="content-card g01-checklist-panel"><div className="section-heading"><div><span className="eyebrow">VERIFICATION CHECKLIST</span><h2>AI 教学内容核验清单</h2></div><span className={`status-pill ${checklistComplete ? 'completed' : 'blocked'}`}>{progress.checklist.length} 项</span></div><div className="g01-checklist-list">{progress.checklist.map((item, index) => <article key={item.id}><div className="g01-check-number">{String(index + 1).padStart(2, '0')}</div><label className="field"><span>类别</span><select value={item.category} onChange={(event) => onUpdateChecklist(item.id, { category: event.target.value as G01ChecklistCategory })}>{checklistCategories.map((category) => <option key={category}>{category}</option>)}</select></label><TextField label="检查项" rows={2} value={item.checkItem} onChange={(checkItem) => onUpdateChecklist(item.id, { checkItem })} /><TextField label="核验证据" rows={2} value={item.evidence} onChange={(evidence) => onUpdateChecklist(item.id, { evidence })} /><TextField label="处理方式" rows={2} value={item.handling} onChange={(handling) => onUpdateChecklist(item.id, { handling })} />{progress.checklist.length > 8 && <button className="ghost-button" type="button" onClick={() => onRemoveChecklist(item.id)}>删除</button>}</article>)}</div></section>
    <section className="content-card g01-contribution-panel"><div className="section-heading"><div><span className="eyebrow">CONTRIBUTIONS</span><h2>个人贡献记录</h2></div><span className={`status-pill ${contributionComplete ? 'completed' : 'blocked'}`}>{contributionComplete ? '齐全' : '待补充'}</span></div><div className="g01-contribution-grid">{progress.contributions.map((item) => { const editable = item.source !== '模拟组员摘要'; return <article key={item.participantId}><div><strong>{item.participantName}</strong><small>{item.source}</small></div><label className="field"><span>本次角色</span><select disabled={!editable} value={item.role ?? ''} onChange={(event) => onUpdateContribution(item.participantId, { role: event.target.value as GroupRole })}><option value="">请选择</option>{groupRoles.map((role) => <option key={role}>{role}</option>)}</select></label><TextField label="具体贡献" disabled={!editable} value={item.contribution} onChange={(contribution) => onUpdateContribution(item.participantId, { contribution })} /></article> })}</div></section>
    <div className="page-actions"><span>{checklistComplete && contributionComplete ? '五类清单与全员贡献均已完整' : '请补齐清单五类覆盖及每位成员的角色与贡献'}</span><button className="primary-button" type="button" disabled={!checklistComplete || !contributionComplete} onClick={onNext}>进入阶段验收<ArrowRight size={17} /></button></div></>
}

export function G01AssessmentPage({ progress, onSubmit, onUpdateModificationSummary, onReset }: { progress: G01Progress; onSubmit: () => void; onUpdateModificationSummary: (value: string) => void; onReset: () => void }) {
  const conditions = validateG01Assessment(progress); const passed = g01IsCurrentlyPassed(progress); const isRecheck = progress.assessments.length > 0
  const canSubmit = g01PrerequisitesComplete(progress) && !passed && (!isRecheck || Boolean(progress.assessmentModificationSummary.trim()))
  return <><PageHeader eyebrow="步骤 6 / 6 · 阶段验收与补验记录" title="按逐项证据提交阶段验收" description="验收失败保留初验与未通过条件；修改后填写摘要再补验。实质内容或人员变化会使旧通过转为需补验，但历史记录不删除。" aside={<div className="metric-pill"><ShieldCheck size={18} /><span><strong>{progress.currentStatus}</strong><small>无数值评分</small></span></div>} />
    <section className={`result-banner ${passed ? 'passed' : ''}`}>{passed ? <CheckCircle2 size={26} /> : <ClipboardCheck size={26} />}<div><strong>{passed ? 'G01 阶段验收已通过' : `当前状态：${progress.currentStatus}`}</strong><p>{passed ? '当前人员、成果内容与最新通过快照一致；只计入阶段验收完成数。' : '四条正式验收条件与成果完整性将分别显示，不产生 10 分制成绩。'}</p></div><span>{progress.groupName}</span></section>
    <section className="content-card g01-assessment-panel"><div className="section-heading"><div><span className="eyebrow">RULE CHECK</span><h2>逐项验收证据</h2></div><span>{conditions.filter((item) => item.passed).length} / {conditions.length} 项通过</span></div><div className="g01-condition-list">{conditions.map((item, index) => <article className={item.passed ? 'passed' : 'failed'} key={item.id}>{item.passed ? <CheckCircle2 size={19} /> : <XCircle size={19} />}<div><span>{item.source === '三日方案验收条件' ? `正式条件 ${index + 1}` : '成果完整性'}</span><strong>{item.label}</strong><small>{item.evidence}</small></div></article>)}</div><div className="g01-artifact-preview"><strong>本次快照恰好归档三项</strong>{g01OutputNames.map((name) => <span key={name}><FileCheck2 size={16} />{name}</span>)}</div>
      {isRecheck && !passed && <TextField label="修改摘要（补验必填）" value={progress.assessmentModificationSummary} onChange={onUpdateModificationSummary} />}
      <div className="inline-actions g01-submit-actions"><button className="secondary-button" type="button" onClick={onReset}><RefreshCw size={16} />重置当前小组 G01</button><button className="primary-button" type="button" disabled={!canSubmit} onClick={onSubmit}><FileCheck2 size={17} />{isRecheck ? '提交补验' : '提交初验'}</button></div>
    </section>
    <section className="content-card g01-history"><div className="section-heading"><div><span className="eyebrow">AUDIT TRAIL</span><h2>初验与补验历史</h2></div><History size={19} /></div>{progress.assessments.length === 0 ? <p className="muted-copy">尚未提交阶段验收。</p> : <div>{progress.assessments.map((record) => <article key={record.assessmentId}><span className={`status-pill ${record.outcome === '已通过' ? 'completed' : 'blocked'}`}>{record.phase} · {record.outcome}</span><div><strong>{record.assessmentId}</strong><small>{record.submittedAt} · {record.assessor} · {record.method}</small><p>成果指纹：{record.fingerprint}</p><p>未通过条件：{record.failedConditionIds.length ? record.failedConditionIds.join('、') : '无'}</p><p>修改摘要：{record.modificationSummary || '初验无修改摘要'}</p></div><em>{record.artifacts.length} 项成果快照</em></article>)}</div>}</section></>
}
