import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, FileCheck2, FilePenLine, FileText, GitBranch, RefreshCw, RotateCcw, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { ValidationNotice } from '../components/ValidationNotice'
import { m04CorrectionLabels, sectionsForCorrection } from '../m04/data'
import { buildM04PeerArtifacts } from '../m04/peerArtifacts'
import type { M04CorrectionRecord, M04CorrectionType, M04InputSnapshot, M04PeerReview, M04Progress, M04Route, M04ScoreResult } from '../m04/types'
import { confirmedM04PlanIsCurrent, latestM04AssessmentIsCurrent, lessonPlanDuration, lessonPlanMappingsComplete, validateM04AssessmentSubmission, validateM04Audit, validateM04Confirmation, validateM04Draft, validateM04Input, validateM04PeerReview } from '../m04/validation'
import { currentParticipant } from '../training/participants'
import { trainingTasks } from '../training/catalog'
import type { ParticipantDirectory } from '../training/types'
import type { GroupRole } from '../types'

const groupRoles: GroupRole[] = ['协调员', '操作员', '核验员', '记录员', '展示员', '学生体验员']
const correctionTypes: M04CorrectionType[] = ['difficulty', 'activity', 'professional']

function TextField({ label, value, onChange, rows = 3, placeholder, disabled = false }: { label: string; value: string; onChange: (value: string) => void; rows?: number; placeholder?: string; disabled?: boolean }) {
  return <label className="field"><span>{label}</span><textarea rows={rows} value={value} placeholder={placeholder} disabled={disabled} onChange={(event) => onChange(event.target.value)} /></label>
}

export function M04Overview({ onNext }: { onNext: () => void }) {
  return <>
    <PageHeader eyebrow="步骤 1 / 7 · 任务说明" title="AI 辅助教案编制" description="围绕一节 45—90 分钟课，形成目标、活动、评价与分层支持对应的教案草稿，经人工审校和同组互评后形成教师确认版。" aside={<div className="metric-pill"><FilePenLine size={18} /><span><strong>105 分钟</strong><small>个人主作 · 小组互评</small></span></div>} />
    <section className="content-card m04-flow-card"><div className="section-heading"><div><span className="eyebrow">CLOSED LOOP</span><h2>从提示词成果到教师责任确认</h2></div></div><div className="m04-flow-grid">{[
      ['01', '确认输入'], ['02', '可选复用'], ['03', '教案草稿'], ['04', '人工审校'], ['05', '同组互评'], ['06', '教师确认'], ['07', '评分归档'],
    ].map(([number, label]) => <article key={number}><span>{number}</span><strong>{label}</strong></article>)}</div></section>
    <div className="m04-overview-grid"><section className="content-card"><span className="eyebrow">成果恰好三项</span><h2>可追溯版本链</h2><div className="output-list">{trainingTasks.M04.outputs.map((item) => <span key={item}><FileText size={16} />{item}</span>)}</div></section><section className="content-card"><span className="eyebrow">通关门槛</span><h2>五项各 0—2 分</h2><p className="muted-copy">总分至少 8 分；专业准确与证据、人工核验与迭代、隐私版权伦理与安全必须各 2 分，且四项核心步骤全部通过。</p></section></div>
    <div className="page-actions"><span>M03 仅为推荐复用来源，不限制 M04 开始或通关</span><button className="primary-button" type="button" onClick={onNext}>确认教案输入<ArrowRight size={17} /></button></div>
  </>
}

export function M04InputPage({ progress, m03Passed, sourceCurrent = m03Passed, onReuseM03, onUpdate, onNext }: { progress: M04Progress; m03Passed: boolean; sourceCurrent?: boolean; onReuseM03: () => void; onUpdate: (patch: Partial<M04InputSnapshot>) => void; onNext: () => void }) {
  const validation = validateM04Input(progress)
  return <>
    <PageHeader eyebrow="步骤 2 / 7 · 教案输入确认" title="确认课程输入与课堂实施条件" description="任务内已提供可编辑的课程、学情、目标与材料基线；如 M03 已完成，可一键复用其当前成果，但不影响 M04 独立完成。" aside={<button className="secondary-button" type="button" disabled={!m03Passed} onClick={onReuseM03}><RefreshCw size={16} />{m03Passed ? '读取 M03 当前成果' : 'M03 暂无可复用成果'}</button>} />
    <section className="content-card m04-source-card"><div className="section-heading"><div><span className="eyebrow">INPUT SOURCE</span><h2>教案输入来源</h2></div><span className={progress.input.sourceConfirmed ? 'status-pill completed' : 'status-pill blocked'}>{progress.input.sourceConfirmed ? '已确认' : '待确认'}</span></div><div className="m04-source-grid"><span><small>来源编号</small><strong>{progress.input.sourceM03AssessmentId || '—'}</strong></span><span><small>输入版本</small><strong>{progress.input.sourceM03RunId || '—'}</strong></span></div><p className="muted-copy">{sourceCurrent ? '当前内容来自 M03 有效成果。' : '当前使用 M04 任务内输入，不代表 M03 已完成。'}</p>{progress.input.sourcePromptSummary && <pre>{progress.input.sourcePromptSummary}</pre>}</section>
    <section className="content-card m04-input-form"><div className="section-heading"><div><span className="eyebrow">CLASS CONTEXT</span><h2>课程与课堂条件</h2></div></div><div className="form-grid three-columns"><TextField label="课程名称（必填）" rows={2} value={progress.input.courseName} onChange={(courseName) => onUpdate({ courseName })} /><TextField label="课次（必填）" rows={2} value={progress.input.lessonName} onChange={(lessonName) => onUpdate({ lessonName })} /><label className="field"><span>课堂时长（45—90 分钟）</span><input type="number" min="45" max="90" value={progress.input.duration} onChange={(event) => onUpdate({ duration: Number(event.target.value) })} /></label></div><div className="form-grid"><TextField label="授课对象（必填）" value={progress.input.audience} onChange={(audience) => onUpdate({ audience })} /><TextField label="学生基础（必填）" value={progress.input.studentFoundation} onChange={(studentFoundation) => onUpdate({ studentFoundation })} /></div><TextField label="教学目标（必填）" value={progress.input.teachingObjective} onChange={(teachingObjective) => onUpdate({ teachingObjective })} /><TextField label="真实工作任务（必填）" value={progress.input.realWorkTask} onChange={(realWorkTask) => onUpdate({ realWorkTask })} /><div className="form-grid"><TextField label="设备限制（必填）" value={progress.input.equipmentConstraints} onChange={(equipmentConstraints) => onUpdate({ equipmentConstraints })} /><TextField label="资源限制（必填）" value={progress.input.resourceConstraints} onChange={(resourceConstraints) => onUpdate({ resourceConstraints })} /></div></section>
    <section className="content-card m04-input-form"><div className="section-heading"><div><span className="eyebrow">COURSE MATERIAL</span><h2>课程材料与允许范围</h2></div></div><TextField label="材料名称（必填）" rows={2} value={progress.input.materialName} onChange={(materialName) => onUpdate({ materialName })} /><TextField label="课程材料正文（必填）" rows={5} value={progress.input.materialContent} onChange={(materialContent) => onUpdate({ materialContent })} /><TextField label="允许使用范围（必填）" value={progress.input.materialScope} onChange={(materialScope) => onUpdate({ materialScope })} /><div className="confirmation-list"><label><input type="checkbox" checked={progress.input.sourceConfirmed} onChange={(event) => onUpdate({ sourceConfirmed: event.target.checked })} /><span><strong>当前教案输入已确认</strong><small>任务内输入或 M03 复用内容均须由教师确认</small></span></label><label><input type="checkbox" checked={progress.input.rightsConfirmed} onChange={(event) => onUpdate({ rightsConfirmed: event.target.checked })} /><span><strong>材料来源与权限已确认</strong><small>不使用未授权教材全文或素材</small></span></label><label><input type="checkbox" checked={progress.input.privacyConfirmed} onChange={(event) => onUpdate({ privacyConfirmed: event.target.checked })} /><span><strong>未包含真实学生敏感信息</strong><small>使用匿名或虚构课堂信息</small></span></label></div></section>
    <ValidationNotice messages={validation.messages} success="课程输入、材料和课堂限制完整，可以生成教案草稿。" />
    <div className="page-actions"><span>不设置规范未要求的字数门槛</span><button className="primary-button" type="button" disabled={!validation.valid} onClick={onNext}>生成 AI 教案草稿<ArrowRight size={17} /></button></div>
  </>
}

function PlanPreview({ progress, confirmed = false }: { progress: M04Progress; confirmed?: boolean }) {
  const plan = confirmed ? progress.confirmedPlan : progress.draft
  if (!plan) return <div className="m04-plan-empty"><FileText size={25} /><strong>{confirmed ? '尚未形成教师确认版' : '尚未生成 AI 草稿'}</strong></div>
  const sectionContent = (id: string, fallback: string) => plan.sections.find((item) => item.id === id)?.content ?? fallback
  const appliedCorrections = progress.confirmedPlan?.appliedCorrections ?? []
  return <div className="m04-plan-preview"><div className="m04-plan-meta"><span>{confirmed ? '教师确认版' : 'AI 草稿'}</span><strong>{plan.input.courseName} · {plan.input.lessonName}</strong><small>{plan.input.duration} 分钟 · {plan.input.audience}</small></div><section><h3>学情分析</h3><p>{sectionContent('learner-analysis', plan.learnerAnalysis)}</p></section><section><h3>3 个学习目标</h3><div className="m04-objective-list">{plan.objectives.map((item, index) => <article key={item.id}><span>目标 {index + 1}</span><strong>{sectionContent(item.id, item.content)}</strong><p>{item.observableEvidence}</p></article>)}</div></section><section><h3>活动—目标—评价对应</h3><div className="m04-activity-table">{plan.activities.map((activity) => <article key={activity.id}><div><span>{activity.minutes} 分钟</span><strong>{activity.title}</strong></div><p><b>教师</b>{activity.teacherAction}</p><p><b>学生</b>{activity.studentTask}</p><p><b>检查</b>{activity.checkMethod}</p>{confirmed && appliedCorrections.some((item) => item.sectionId === activity.id) && <p><b>确认</b>{sectionContent(activity.id, activity.studentTask)}</p>}<small>对应 {activity.objectiveIds.join('、')}</small></article>)}</div></section><section><h3>评价证据</h3><div className="m04-compact-list">{plan.assessments.map((item) => <span key={item.id}><strong>{item.method}</strong>{sectionContent(item.id, item.evidence)}<small>{item.objectiveIds.join('、')} · {item.activityIds.join('、')}</small></span>)}</div></section><section><h3>分层支持</h3><div className="m04-support-grid">{plan.supports.map((item) => <article key={item.id}><strong>{item.learnerLevel}</strong><p>{sectionContent(item.id, item.strategy)}</p><small>{item.objectiveIds.join('、')} · {item.activityIds.join('、')}</small></article>)}</div></section><section><h3>专业与安全说明</h3><p>{sectionContent('professional-note', '')}</p></section>{confirmed && <section><h3>人工修改追踪</h3><div className="m04-compact-list">{appliedCorrections.map((item) => <span key={item.type}><strong>{m04CorrectionLabels[item.type]}</strong>{item.revisedContent}<small>依据：{item.basis}</small></span>)}</div></section>}</div>
}

export function M04DraftPage({ progress, running, onRun, onNext }: { progress: M04Progress; running: boolean; onRun: () => void; onNext: () => void }) {
  const validation = validateM04Draft(progress)
  return <>
    <PageHeader eyebrow="步骤 3 / 7 · AI 草稿" title="生成结构化教案草稿" description="同一输入快照生成目标、活动、评价和分层支持。AI 原草稿与教师修改记录分开保存。" />
    <div className="m04-draft-layout"><section className="content-card m04-generation-panel"><span className="eyebrow">DETERMINISTIC RUNNER</span><h2>确定性本地教案生成</h2><p>生成 3 个可观察目标、课堂活动、评价证据与分层支持；不连接真实模型、Dify、后端或 API Key。</p><div className="m04-generation-facts"><span><small>课堂时长</small><strong>{progress.input.duration} 分钟</strong></span><span><small>目标数量</small><strong>3 个</strong></span><span><small>设备边界</small><strong>{progress.input.equipmentConstraints}</strong></span></div><button className="primary-button full-button" type="button" disabled={running || Boolean(progress.draft)} onClick={onRun}><Sparkles size={17} />{running ? '正在生成…' : progress.draft ? 'AI 草稿已生成并锁定' : '生成 AI 教案草稿'}</button></section><section className="content-card"><PlanPreview progress={progress} /></section></div>
    {progress.draft && <ValidationNotice messages={validation.messages} success={`教案草稿结构完整，活动时间合计 ${lessonPlanDuration(progress.draft)} 分钟，五类要素对应关系已建立。`} />}
    <div className="page-actions"><span>{progress.draft ? `草稿 ${progress.draft.planId} 已本地保存` : '等待生成 AI 原始草稿'}</span><button className="primary-button" type="button" disabled={!validation.valid} onClick={onNext}>开始逐项人工审校<ArrowRight size={17} /></button></div>
  </>
}

function CorrectionEditor({ type, progress, onUpdate }: { type: M04CorrectionType; progress: M04Progress; onUpdate: (patch: Partial<M04CorrectionRecord>) => void }) {
  const record = progress.audit.corrections[type]
  const sections = progress.draft ? sectionsForCorrection(progress.draft, type) : []
  function selectSection(sectionId: string) {
    const section = sections.find((item) => item.id === sectionId)
    onUpdate({ sectionId, originalContent: section?.content ?? '', revisedContent: '', basis: '' })
  }
  return <article className="content-card m04-correction-card"><div className="section-heading"><div><span className="eyebrow">{type.toUpperCase()}</span><h2>{m04CorrectionLabels[type]}</h2></div><span className={record.revisedContent.trim() && record.basis.trim() ? 'status-pill completed' : 'status-pill blocked'}>{record.revisedContent.trim() && record.basis.trim() ? '已记录' : '必做'}</span></div><label className="field"><span>选择要修改的草稿段落</span><select value={record.sectionId} onChange={(event) => selectSection(event.target.value)}><option value="">请选择</option>{sections.map((section) => <option value={section.id} key={section.id}>{section.title}</option>)}</select></label><TextField label="AI 原内容（自动保存）" rows={4} value={record.originalContent} onChange={() => undefined} disabled /><TextField label="教师修改后内容（必填）" rows={4} value={record.revisedContent} onChange={(revisedContent) => onUpdate({ revisedContent })} /><TextField label="修改依据（必填）" value={record.basis} onChange={(basis) => onUpdate({ basis })} placeholder="课程材料条目、学生基础、设备或课时条件" /></article>
}

export function M04AuditPage({ progress, onObjectiveCheck, onActivityCheck, onUpdateFlags, onUpdateCorrection, onNext }: { progress: M04Progress; onObjectiveCheck: (id: string, checked: boolean) => void; onActivityCheck: (id: string, value: M04Progress['audit']['activityChecks'][string]) => void; onUpdateFlags: (patch: Partial<M04Progress['audit']>) => void; onUpdateCorrection: (type: M04CorrectionType, patch: Partial<M04CorrectionRecord>) => void; onNext: () => void }) {
  const validation = validateM04Audit(progress)
  return <>
    <PageHeader eyebrow="步骤 4 / 7 · 人工审校" title="逐项核对教案结构与课堂条件" description="核对目标、活动、评价、分层支持和课堂实施条件，并保留难度、课堂活动、专业表述三类人工修改记录。" />
    <section className="content-card m04-audit-checks"><div className="section-heading"><div><span className="eyebrow">OBJECTIVES</span><h2>3 个目标可观察、可评价检查</h2></div><span>{Object.values(progress.audit.objectiveChecks).filter(Boolean).length} / 3</span></div><div className="confirmation-list">{progress.draft?.objectives.map((item, index) => <label key={item.id}><input type="checkbox" checked={Boolean(progress.audit.objectiveChecks[item.id])} onChange={(event) => onObjectiveCheck(item.id, event.target.checked)} /><span><strong>目标 {index + 1}：{item.content}</strong><small>观察证据：{item.observableEvidence}</small></span></label>)}</div></section>
    <section className="content-card m04-audit-checks"><div className="section-heading"><div><span className="eyebrow">ACTIVITIES</span><h2>活动可实施性逐项检查</h2></div><span>{lessonPlanDuration(progress.draft)} / {progress.input.duration} 分钟</span></div><div className="m04-activity-audit">{progress.draft?.activities.map((item) => <article key={item.id}><div><span>{item.minutes} 分钟</span><strong>{item.title}</strong></div><p>{item.studentTask}</p><label className="field"><span>可实施性</span><select value={progress.audit.activityChecks[item.id] ?? ''} onChange={(event) => onActivityCheck(item.id, event.target.value as M04Progress['audit']['activityChecks'][string])}><option value="">请选择</option><option>可实施</option><option>需调整</option><option>不可实施</option></select></label></article>)}</div><div className="confirmation-list m04-limit-checks">{[
      ['durationChecked', '课时限制已核对', `活动合计 ${lessonPlanDuration(progress.draft)} 分钟`], ['equipmentChecked', '设备条件已核对', progress.input.equipmentConstraints], ['resourcesChecked', '资源条件已核对', progress.input.resourceConstraints], ['materialVerified', '专业内容已回到课程材料核验', progress.input.materialName], ['safetyVerified', '专业操作与安全边界已核验', '危险操作不得采用未经核验内容'],
    ].map(([field, label, detail]) => <label key={field}><input type="checkbox" checked={Boolean(progress.audit[field as keyof M04Progress['audit']])} onChange={(event) => onUpdateFlags({ [field]: event.target.checked })} /><span><strong>{label}</strong><small>{detail}</small></span></label>)}</div></section>
    <div className="m04-correction-grid">{correctionTypes.map((type) => <CorrectionEditor type={type} progress={progress} onUpdate={(patch) => onUpdateCorrection(type, patch)} key={type} />)}</div>
    <ValidationNotice messages={validation.messages} success="教案结构与课堂条件均已核对，三类人工修改记录完整。" />
    <div className="page-actions"><span>“需调整”是有效检查结果，但必须通过修改记录解决关键问题</span><button className="primary-button" type="button" disabled={!validation.valid} onClick={onNext}>进入小组互评<ArrowRight size={17} /></button></div>
  </>
}

export function M04PeerReviewPage({ progress, directory, onUpdate, onSubmit, onNext }: { progress: M04Progress; directory: ParticipantDirectory; onUpdate: (patch: Partial<M04PeerReview>) => void; onSubmit: () => void; onNext: () => void }) {
  const identity = currentParticipant(directory)
  const artifacts = buildM04PeerArtifacts(directory)
  const selected = artifacts.find((item) => item.participantId === progress.peerReview.targetParticipantId && item.artifactId === progress.peerReview.targetArtifactId)
  const validation = validateM04PeerReview(progress, directory)
  return <>
    <PageHeader eyebrow="步骤 5 / 7 · 小组互评" title="按目标—活动—评价一致性检查组员教案" description="只能选择当前同组其他成员。互评判断允许指出问题，有效性取决于对象、字段和可执行建议完整，不以正面评价为条件。" aside={<div className="metric-pill"><UsersRound size={18} /><span><strong>{identity?.groupName ?? '未分组'}</strong><small>{artifacts.length} 份模拟教案</small></span></div>} />
    <div className="review-source-note"><RefreshCw size={18} /><div><strong>无多人后端的模拟组员成果</strong><p>教案摘要按人员 ID 确定性生成并受同组过滤；正式系统应按 participantId + groupId + taskId + artifactId 读取真实提交。</p></div></div>
    <section className="content-card review-form"><div className="section-heading"><div><span className="eyebrow">PEER LESSON PLAN</span><h2>选择同组教案</h2></div><span className="identity-readonly">互评人：{identity?.name ?? '未选择'}</span></div><div className="form-grid three-columns"><label className="field"><span>本次承担角色</span><select value={progress.peerReview.reviewerRole ?? ''} onChange={(event) => onUpdate({ reviewerRole: event.target.value as GroupRole, submitted: false })}><option value="">请选择</option>{groupRoles.map((role) => <option key={role}>{role}</option>)}</select><small>仅对 M04 有效，不写入人员档案</small></label><label className="field"><span>被互评成员</span><select value={progress.peerReview.targetParticipantId} onChange={(event) => { const artifact = artifacts.find((item) => item.participantId === event.target.value); onUpdate({ targetParticipantId: event.target.value, targetArtifactId: artifact?.artifactId ?? '', submitted: false }) }}><option value="">请选择同组其他成员</option>{artifacts.map((item) => <option value={item.participantId} key={item.participantId}>{item.participantName}</option>)}</select></label><label className="field"><span>关联教案成果</span><select disabled={!selected} value={progress.peerReview.targetArtifactId} onChange={(event) => onUpdate({ targetArtifactId: event.target.value, submitted: false })}><option value="">请选择</option>{selected && <option value={selected.artifactId}>AI 草稿与审校记录</option>}</select></label></div>{selected && <div className="m04-peer-preview"><div><span>{selected.duration} 分钟</span><strong>{selected.courseName} · {selected.lessonName}</strong></div><p><b>目标</b>{selected.objectiveSummary}</p><p><b>活动</b>{selected.activitySummary}</p><p><b>评价</b>{selected.assessmentSummary}</p><p><b>分层</b>{selected.supportSummary}</p></div>}<div className="form-grid"><label className="field"><span>整体可实施性</span><select value={progress.peerReview.overallImplementability} onChange={(event) => onUpdate({ overallImplementability: event.target.value as M04PeerReview['overallImplementability'], submitted: false })}><option value="">请选择</option><option>可实施</option><option>需调整</option><option>不可实施</option></select></label>{[
      ['objectiveActivityAssessment', '目标—活动—评价是否一致'], ['objectiveObservable', '目标是否可观察评价'], ['activityFeasible', '活动是否符合课时设备条件'], ['differentiatedSupport', '分层支持是否对应目标与活动'],
    ].map(([field, label]) => <label className="field" key={field}><span>{label}</span><select value={String(progress.peerReview[field as keyof M04PeerReview] ?? '')} onChange={(event) => onUpdate({ [field]: event.target.value, submitted: false })}><option value="">请选择</option><option>一致</option><option>部分一致</option><option>不一致</option></select></label>)}</div><TextField label="可执行的互评建议（必填）" value={progress.peerReview.suggestion} onChange={(suggestion) => onUpdate({ suggestion, submitted: false })} /></section>
    <ValidationNotice messages={validation.messages} success="同组教案、可实施性、一致性检查和可执行建议已经提交。" />
    <div className="page-actions"><span>人员或分组变化后旧互评自动失效</span><div className="inline-actions"><button className="secondary-button" type="button" disabled={!progress.peerReview.reviewerRole || !selected || !progress.peerReview.overallImplementability || !progress.peerReview.objectiveActivityAssessment || !progress.peerReview.objectiveObservable || !progress.peerReview.activityFeasible || !progress.peerReview.differentiatedSupport || !progress.peerReview.suggestion.trim()} onClick={onSubmit}>{progress.peerReview.submitted ? '重新提交互评' : '提交互评'}</button><button className="primary-button" type="button" disabled={!validation.valid} onClick={onNext}>形成教师确认版<ArrowRight size={17} /></button></div></div>
  </>
}

export function M04ConfirmationPage({ progress, directory, onUpdate, onConfirm, onNext }: { progress: M04Progress; directory: ParticipantDirectory; onUpdate: (patch: Partial<M04Progress['confirmation']>) => void; onConfirm: () => void; onNext: () => void }) {
  const validation = validateM04Confirmation(progress, directory)
  const current = confirmedM04PlanIsCurrent(progress, directory)
  return <>
    <PageHeader eyebrow="步骤 6 / 7 · 教师确认版" title="处理互评意见并承担最终确认责任" description="教师确认版由 AI 原草稿、三类人工审校和同组互评共同形成；AI 不替代教师确认专业事实、课堂可实施性和安全边界。" />
    <section className="content-card m04-peer-response"><div className="section-heading"><div><span className="eyebrow">PEER FEEDBACK</span><h2>互评意见处理</h2></div><span>{progress.peerReview.suggestion || '尚无互评建议'}</span></div><div className="form-grid"><label className="field"><span>处理方式</span><select value={progress.confirmation.peerDisposition} onChange={(event) => onUpdate({ peerDisposition: event.target.value as M04Progress['confirmation']['peerDisposition'] })}><option value="">请选择</option><option>采纳并已核对</option><option>部分采纳并已核对</option><option>说明后不采纳</option></select></label><TextField label="处理说明与依据（必填）" value={progress.confirmation.peerResponse} onChange={(peerResponse) => onUpdate({ peerResponse })} /></div><div className="confirmation-list">{[
      ['professionalConfirmed', '专业准确由教师最终确认', progress.input.materialName], ['implementationConfirmed', '课堂可实施性由教师最终确认', `${progress.input.duration} 分钟及现有设备资源条件`], ['safetyConfirmed', '隐私、版权、伦理与安全由教师最终确认', '不含真实学生身份、未授权素材或危险操作'],
    ].map(([field, label, detail]) => <label key={field}><input type="checkbox" checked={Boolean(progress.confirmation[field as keyof M04Progress['confirmation']])} onChange={(event) => onUpdate({ [field]: event.target.checked })} /><span><strong>{label}</strong><small>{detail}</small></span></label>)}</div><div className="inline-actions"><button className="primary-button" type="button" disabled={!validation.valid} onClick={onConfirm}><FileCheck2 size={17} />{current ? '重新生成当前教师确认版' : '生成教师确认版'}</button></div></section>
    <section className="content-card"><PlanPreview progress={progress} confirmed /></section>
    <div className="page-actions"><span>{current ? '教师确认版与当前审校、互评记录一致' : '内容变化后旧确认版不会作为当前验收依据'}</span><button className="primary-button" type="button" disabled={!current} onClick={onNext}>进入评分与成果<ArrowRight size={17} /></button></div>
  </>
}

export function M04ResultPage({ progress, result, directory, onNavigate, onSubmitAssessment, onUpdateModificationSummary, onReset }: { progress: M04Progress; result: M04ScoreResult; directory: ParticipantDirectory; onNavigate: (route: M04Route) => void; onSubmitAssessment: () => void; onUpdateModificationSummary: (value: string) => void; onReset: () => void }) {
  const latest = progress.assessments.at(-1)
  const currentPassed = latestM04AssessmentIsCurrent(progress, directory)
  const canSubmit = validateM04AssessmentSubmission(progress, directory).valid
  return <>
    <PageHeader eyebrow="步骤 7 / 7 · 评分与成果" title={currentPassed ? 'M04 任务已通过' : latest ? 'M04 复验准备' : 'M04 任务结果检查'} description="系统按当前输入、AI 草稿、人工审校、互评和教师确认版实时计算；提交验收后形成不可变评分快照。" aside={<div className={currentPassed ? 'result-score passed' : 'result-score'}><strong>{result.total}</strong><span>/ 10 分</span></div>} />
    <section className={currentPassed ? 'result-banner passed' : 'result-banner'}>{currentPassed ? <ShieldCheck size={28} /> : <AlertTriangle size={28} />}<div><strong>{currentPassed ? '任务通过：形成经人工审校的教师确认版教案' : '尚未形成当前有效的通过快照'}</strong><p>总分 ≥ 8，四项核心步骤通过，且专业证据、人工核验迭代和安全均为 2 分。</p></div><span>{result.coreRequirements.filter((item) => item.passed).length} / 4 项核心要求</span></section>
    <div className="score-layout"><section className="content-card score-card"><div className="section-heading"><div><span className="eyebrow">过程质量评分</span><h2>五项标准</h2></div></div><div className="dimension-list">{result.dimensions.map((dimension) => <div className="dimension-row" key={dimension.id}><span className={`score-dot score-${dimension.score}`}>{dimension.score}</span><div><strong>{dimension.label}</strong><p>{dimension.evidence}</p></div><div className="mini-score-track"><span style={{ width: `${dimension.score * 50}%` }} /></div></div>)}</div></section><section className="content-card requirement-card"><div className="section-heading"><div><span className="eyebrow">通关门槛</span><h2>核心步骤</h2></div></div><div className="requirement-list">{result.coreRequirements.map((requirement) => <button type="button" key={requirement.id} className={requirement.passed ? 'passed' : ''} onClick={() => onNavigate(requirement.route)}>{requirement.passed ? <CheckCircle2 size={19} /> : <AlertTriangle size={19} />}<span><strong>{requirement.label}</strong><small>{requirement.passed ? '已完成' : '点击前往补充'}</small></span>{!requirement.passed && <ArrowRight size={16} />}</button>)}</div></section></div>
    <section className="content-card artifact-section"><div className="section-heading"><div><span className="eyebrow">任务成果</span><h2>恰好三项成果</h2></div></div><div className="m03-artifact-grid">{trainingTasks.M04.outputs.map((name, index) => <article key={name}>{[<Sparkles size={20} />, <FilePenLine size={20} />, <FileCheck2 size={20} />][index]}<strong>{name}</strong><p>{index === 0 ? '保存生成输入、结构化内容和 AI 原始版本。' : index === 1 ? '保存三处原文、修改后内容、依据及互评记录。' : '保存教师最终确认、意见处理和版本来源。'}</p></article>)}</div></section>
    <section className="content-card m03-assessment-panel"><div className="section-heading"><div><span className="eyebrow">ASSESSMENT HISTORY</span><h2>验收与复验留痕</h2></div><span>{progress.assessments.length} 次提交</span></div>{progress.assessments.length > 0 && <div className="m03-assessment-history">{progress.assessments.map((assessment, index) => <article key={assessment.assessmentId}><span>{index === 0 ? '初验' : `复验 ${index}`}</span><strong>{assessment.total} / 10 · {assessment.passed ? '通过' : '未通过'}</strong><small>{new Date(assessment.submittedAt).toLocaleString('zh-CN')} · {assessment.engine}</small>{assessment.modificationSummary && <p>{assessment.modificationSummary}</p>}</article>)}</div>}{progress.assessments.length > 0 && !currentPassed && <TextField label="本轮修改摘要（再次验收必填）" rows={2} value={progress.assessmentModificationSummary} onChange={onUpdateModificationSummary} />}{!currentPassed && <div className="inline-actions"><button className="primary-button" type="button" disabled={!canSubmit || (progress.assessments.length > 0 && !progress.assessmentModificationSummary.trim())} onClick={onSubmitAssessment}><ClipboardCheck size={17} />{progress.assessments.length > 0 ? '提交复验' : '提交验收'}</button></div>}</section>
    <div className="page-actions"><span>{currentPassed ? '三项成果已自动同步到成果中心；M05 可选择复用当前教案' : 'M04 实质内容变化后旧验收保留，但不作为当前完成状态'}</span><button className="secondary-button" type="button" onClick={onReset}><RotateCcw size={16} />重置 M04</button></div>
  </>
}

export function M04AlignmentSummary({ progress }: { progress: M04Progress }) {
  return <div className="m04-alignment-summary"><GitBranch size={18} /><span><strong>对应关系检查</strong><small>{lessonPlanMappingsComplete(progress.draft) ? '目标、活动、评价、分层支持完整连接' : '仍有关系未连接'}</small></span></div>
}

